# Generated by Django 5.2.1 on 2025-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('people_detected', models.IntegerField()),
                ('frame_processed', models.BooleanField(default=True)),
            ],
        ),
    ]
